spring:
  datasource:
    url: jdbc:mysql://rebora.cubzbc1hlyxy.ap-northeast-2.rds.amazonaws.com:3306/rebora_dev?enabledTLSProtocols=TLSv1.2&characterEncoding=utf-8&autoReconnect=TRUE&rewriteBatchedStatements=true&serverTimezone=Asia/Seoul
    username: moskastudio
    password: moskastudio~!1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 500
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        max-page-size: 100
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    path match:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true


logging:
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter : DEBUG

jwt:
  header: Authorization
  secret: 65E7CD943CF85FA177D2D81D99ECEF92FA34F49B5C72B313927F3A3627
  token-validity-in-seconds: 86400

server:
  error:
    include-exception: true
  ssl:
    enabled: false
    key-store: classpath:m.re-bora.com.jks
    key-store-password: moska~!@1
    key-store-type: jks
  port: 8080
mail:
  username: moskastudio3@gmail.com
  password: ldshulnzexdceelf

cloud:
  aws:
    credentials:
      access-key: AKIATWD4P5YEQHZVBPCE
      secret-key: 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
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: rebora

sns:
  login:
    naver:
      client-id: JSzbJqjUJalGWU8Ssh39
      key: X1xn8OMLWd

toss:
  payments:
    test:
      client-key: test_ck_lpP2YxJ4K875ZWkNeDJVRGZwXLOb
      authorization : dGVzdF9za183WFpZa0tMNE1yak1ESmQ3dlprVjB6SndsRVdSOg==

import:
  auth:
    imp_key: 1552251027035377
    imp_secret: FBVSWCbJTmWqda0ZpZbPZTuhFhLOWyIvTnybuyAmQWACvdZeszaUY7Pp4uLgbNy1RTo3BviNFmAb54f4
