spring:
  datasource:
    url: jdbc:mysql://rebora.cubzbc1hlyxy.ap-northeast-2.rds.amazonaws.com:3306/rebora_test?enabledTLSProtocols=TLSv1.2&characterEncoding=utf-8&autoReconnect=TRUE&rewriteBatchedStatements=true
    username: moskastudio
    password: moskastudio~!1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 500
  data:
    web:
      pageable:
        max-page-size: 100


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: 65E7CD943CF85FA177D2D81D99ECEF92FA34F49B5C72B313927F3A3627
  token-validity-in-seconds: 86400

server:
  error:
    include-exception: true

mail:
  username: kkp02052@gmail.com
  password: jhbpwkcvougoljlx

cloud:
  aws:
    credentials:
      access-key: AKIATWD4P5YEQHZVBPCE
      secret-key: 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
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: rebora
